apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq01
  labels:
    app: rmq01
spec:
  selector:
    matchLabels:
      app: rmq01
  replicas: 1
  template:
    metadata:
      labels:
        app: rmq01
    spec:
      containers:
      - name: rmq01
        image: rabbitmq
        ports:
        - name: rmq01-port
          containerPort: 5672
        env: 
         - name: RABBITMQ_DEFAULT_USER
           value: "test"
         - name: RABBITMQ_DEFAULT_PASS
           value: "test"

